import requests
import json

# Set up the API credentials
access_token = "YOUR_ACCESS_TOKEN"
blog_id = "YOUR_BLOG_ID"

# Set up the headers for the API request
headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}

# Set up the data for the new blog post
data = {
    "title": "My Bot-Generated Blog Post",
    "content": "This is a blog post generated by my bot."
}

# Make a POST request to the Blogger API to create the new blog post
response = requests.post(
    f"https://www.googleapis.com/blogger/v3/blogs/{blog_id}/posts",
    headers=headers,
    data=json.dumps(data)
)

# Print the response from the API
print(response.json())
